### ISSUE TITLE
Two concerns?

### ISSUE THREAD

**Issue by dryruner** [vrolland/tokenSaleDraft#12]
https://github.com/RequestNetwork/RequestTokenSale/blob/c3a2ca409a321e837f62a9a72bad8193da52c7a0/contracts/ProgressiveIndividualCappedCrowdsale.sol#L31

The state change should be made after all checks are passed I think, like:

```
function validPurchase() 
        internal 
        returns(bool)
    {
        require(tx.gasprice <= GAS_LIMIT_IN_WEI);
        uint ethCapPerAddress = getCurrentEthCapPerAddress();
        bool withinCap = participated[msg.sender].add(msg.value) <= ethCapPerAddress;
        if (withinCap) {
            participated[msg.sender] = participated[msg.sender].add(msg.value);
            return super.validPurchase();
        }
        return false;
    }
```

Otherwise if user send > 6.713ETH on 1st day, he won't be able to participate in sale any more.

* Another concern/question I have is: https://github.com/RequestNetwork/RequestTokenSale/blob/ddf5b022bcba83aca3adf4078bf63ba4fbded947/contracts/ProgressiveIndividualCappedCrowdsale.sol#L62,  what is the precedence level of operations?  I'm assuming it should be `return (2 ** (currentPeriod.sub(1))).mul(baseEthCapPerAddress);`, is it? Thanks!

**Comment by vrolland** [comment]
Hello jonnyhsy, thank you for your feedback.

1. An exception will be thrown by a require() in this case (look line 84 in StandardCrowdsale.sol). That will rollback the transaction.

2. first "currentPeriod.sub(1)" then "(2 ** currentPeriod.sub(1))" then (2 ** currentPeriod.sub(1)).mul(baseEthCapPerAddress)

Best,
