### ISSUE TITLE
Conversion rate set in wrong units

### ISSUE THREAD

**Issue by adamkolar** [vrolland/tokenSaleDraft#4]
In the RequestTokenSale contract, there is a constant named RATE_ETH_REQ
```
// Token sale rate from ETH to REQ
uint private constant RATE_ETH_REQ = 5000;
```
that is passed to constructor of the StandardCrowdsale base contract, inside this contract the value is used for conversion from wei to REQ instead of ETH to REQ. In any case, giving 5000 tokens for one wei seems like a lot (considering TOTAL_REQUEST_TOKEN_SUPPLY, it would mean only 200000 wei can be raised), was it intended?

**Comment by vrolland** [comment]
Hello Adamkolar, Thank you for your concern.

Don't forget the decimal on the token contract and the line 44 of this same contract RequestToken.sol : 
totalSupply = tokenTotalAmount * (10 ** decimals);

So, the line you are probably referencing is line 89 of StandardCrowdsale.sol : 
uint256 tokens = weiAmount.mul(rate);
It actually generates tokens with the decimals included.

We reused and modified the Crowdsale.sol by OpenZeppelin (https://github.com/OpenZeppelin/zeppelin-solidity/blob/master/contracts/crowdsale/Crowdsale.sol)
It also the way Kyber handled it for their token sale.(https://github.com/KyberNetwork/TokenDistributionContracts/blob/master/TokenSale/contracts/KyberNetworkTokenSale.sol)

I hope I answered properly to your concern.

Best,
