### ISSUE TITLE
Possible bugs and fixes

### ISSUE THREAD

**Issue by speedyRat** [vrolland/tokenSaleDraft#7]
Hello, 
We would like to list possible bugs that we have found on your smart contracts.
RequestTokenSale.sol

1. You can add a constant called

// Current value is October 17, 2017 10:10:10 Eastern Time.
uint256 becomesTransferable = 1508249410; 

set the date where the tokens will become transferable
and make those checks in transfer() and transferFrom() methods

by calling a method like this
 
  modifier premature(unint256 _time)
{ 
       require(now >= _time)
}

2. The following method of yours has a logical mistake. It should be 
     now >= transferableStartTime.
     Tokens should only be transferable if the current date is greater than the             transferable date. Very big mistake.

  modifier onlyWhenTransferEnabled() 
    {
        if ( now <= transferableStartTime ) {
            require(msg.sender == tokenSaleContract || msg.sender == earlyInvestorWallet || msg.sender == owner);
        }
        _;
    }

3. no way of locking people's balances therefore,  if anything goes wrong we can't freeze someone's account and recover the money

function lockBalance(uint256 _value) {

        // Check if the lock on previously locked tokens is still active.
        if (balanceLocks[msg.sender].unlockDate > now) {
            // Only allow confirming the lock or adding to it.
            require(_value >= balanceLocks[msg.sender].amount);
        }
        // Ensure that no more than the balance can be locked.
        require(balances[msg.sender] >= _value);

        // Lock tokens and notify.
        uint256 _expiry = now + lockingPeriod;
        BalanceLocked(msg.sender, balanceLocks[msg.sender].amount, _value, _expiry);
        balanceLocks[msg.sender] = BalanceLock(_value, _expiry);
    }

4. if you implement the lock balance method then you would need to check the available balance of users.

 function availableBalance(address _owner) constant returns(uint256) {
        if (balanceLocks[_owner].unlockDate < now) {
            return balances[_owner];
        } else {
            assert(balances[_owner] >= balanceLocks[_owner].amount);
            return balances[_owner] - balanceLocks[_owner].amount;
        }
    } function availableBalance(address _owner) constant returns(uint256) {
        if (balanceLocks[_owner].unlockDate < now) {
            return balances[_owner];
        } else {
            assert(balances[_owner] >= balanceLocks[_owner].amount);
            return balances[_owner] - balanceLocks[_owner].amount;
        }
    }

5.  would also need to make this check on transfer() and transferFrom() methods by adding this line : require(availableBalance(msg.sender) >= _value);

6.  Use CDN-service (for example, CloudFlare) to protect against DDoS attacks. It’s better to do this before starting ICO campaigns. Also, close all ports, create IP whitelists, which can be accessed by them.

7.   Rejecting non-zero transfers is not ERC20 compliant. The ERC20 specification states that “transfers of 0 values MUST be treated as normal transfers”.

**Comment by vrolland** [comment]
Hello SpeedyRat, Thank you for your suggestions.

2. This is not a mistake, we check the require() only if it is BEFORE transferableStartTime, after everyone can transfer so there is no need to check the require()
3 4 5. not Specified
6. This doesn't concern the contract
7. Our ERC20 token does not reject transfers of 0 values

Best,
