### ISSUE TITLE
Possible bug

### ISSUE THREAD

**Issue by speedyRat** [vrolland/tokenSaleDraft#9]
function getCurrentEthCapPerAddress() 
        public
        constant
        returns(uint)
    {
        if (block.timestamp < startTime) return 0;
        uint timeSinceStartInSec = block.timestamp.sub(startTime);
        uint currentPeriod = timeSinceStartInSec.div(TIME_PERIOD_IN_SEC).add(1);

        // for currentPeriod > 256 will always return baseEthCapPerAddress
        return (2 ** currentPeriod.sub(1)).mul(baseEthCapPerAddress);
    }

Why isn't there a check to see (if block.timestamp >= endTime) return 0;

**Comment by vrolland** [comment]
This check is done in StandardCrowdsale.sol line 113
